# Welcome to Jekyll!

theme: null
remote_theme: "mmistakes/minimal-mistakes"

plugins:
  - jekyll-remote-theme

# Site Settings
locale: "en-US"
title: "Yubin Kim's Website"
title_separator: "-"
subtitle: ""
name: "Yubin Kim"
description: "Yubin Kim's personal website."
url: "https://cosmos2718.github.io"
baseurl: "/Kimyubin"
repository: "cosmos2718/Kimyubin"
teaser:
logo: "/assets/images/Kimyubin_profile.jpg"
masthead_title: "Yubin Kim"

words_per_minute: 200

# Site Author
author:
  name: "Yubin Kim"
  avatar: "/assets/images/Kimyubin.jpg"
  bio: "Physics student | Astrophysics | Gravitational Waves"
  location: "Seoul, Korea"
  email: "cosmos2718@ewha.ac.kr"
  links:
    - label: "Email"
      icon: "fas fa-fw fa-envelope-square"
      url: "mailto:cosmos2718@ewha.ac.kr"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/cosmos2718"
    - label: "Website"
      icon: "fas fa-fw fa-link"
      url: "https://cosmos2718.github.io/Kimyubin/"

# Enable sidebar with bio and avatar
sidebar:
  nav: "sidebar"
  show_avatar: true
  bio: true

# Footer
footer:
  links:
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/cosmos2718"
    - label: "YouTube"
      icon: "fab fa-fw fa-youtube"
      url: "https://www.youtube.com/@mulli_babo"

# Reading Files
include:
  - .htaccess
  - _pages
exclude:
  - "*.sublime-project"
  - "*.sublime-workspace"
  - vendor
  - .asset-cache
  - .bundle
  - .jekyll-assets-cache
  - .sass-cache
  - assets/js/plugins
  - assets/js/_main.js
  - assets/js/vendor
  - Capfile
  - CHANGELOG
  - config
  - Gemfile
  - Gruntfile.js
  - gulpfile.js
  - LICENSE
  - log
  - node_modules
  - package.json
  - package-lock.json
  - Rakefile
  - README
  - tmp
  - /docs
  - /test
keep_files:
  - .git
  - .svn

encoding: "utf-8"
markdown_ext: "markdown,mkdown,mkdn,mkd,md"

# Conversion
markdown: kramdown
highlighter: rouge
lsi: false
excerpt_separator: "\n\n"
incremental: false

# Markdown Processing
kramdown:
  input: GFM
  hard_wrap: false
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  enable_coderay: false

# Sass/SCSS
sass:
  sass_dir: _sass
  style: compressed

# Layout Defaults
defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      share: true
      related: true
  - scope:
      path: ""
      type: pages
    values:
      layout: single

# Outputting
permalink: /:categories/:title/
paginate: 5
paginate_path: /page:num/
timezone: "Asia/Seoul"

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jekyll-include-cache

whitelist:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jekyll-include-cache

# Archives
category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/

# HTML Compression
compress_html:
  clippings: all
  ignore:
    envs: development
